spring.application.name=jreactivities
server.port=8977
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:6666/jreactivities
spring.datasource.username=postgres
spring.datasource.password=postgres